kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: ping-cloud

commonLabels:
  app: ping-cloud

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: pingcommon-init
  files:
  - scripts/copy-dependencies.sh
  - scripts/wait-for-services.sh
  - scripts/utils.lib.sh

resources:
- namespace.yaml
- rbac.yaml
- secret.yaml
- configmap.yaml
- pingcloud-metadata
- p14c-oauth-service