# A manual backup job - this does the same thing as the CronJob except it may be configured to be triggered in reaction
# to a ClickOps event.
apiVersion: batch/v1
kind: Job
metadata:
  name: pingfederate-backup
spec:
  ttlSecondsAfterFinished: 0
  backoffLimit: 5
  template:
    spec:
      serviceAccount: ping-serviceaccount
      restartPolicy: Never
      containers:
      - name: pingfederate-backup
        image: pingcloud-docker.jfrog.io/pingidentity/pingfederate:10.2.0-SNAPSHOT
        command:
        - /opt/in/backup-archive-data.sh
        envFrom:
        - configMapRef:
            name: pingfederate-environment-variables
        volumeMounts:
        - name: pingfederate-backup
          mountPath: /opt/in/backup-archive-data.sh
          subPath: backup-archive-data.sh
      volumes:
      - name: pingfederate-backup
        configMap:
          name: pingfederate-backup
          defaultMode: 0555